# Generated by Django 5.0.1 on 2024-03-14 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FO_APP', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='type',
        ),
        migrations.AlterField(
            model_name='products',
            name='category',
            field=models.CharField(choices=[('Veg', 'Vegetarian'), ('NonVeg', 'Non-Vegetarian'), ('Drinks', 'Drinks'), ('Starters', 'Starters'), ('Desserts', 'Desserts')], default='Not Mentioned', max_length=50),
        ),
        migrations.AlterField(
            model_name='products',
            name='t_type',
            field=models.CharField(choices=[('All', 'All'), ('Breakfast', 'Breakfast'), ('Lunch', 'Lunch'), ('Dinner', 'Dinner')], default='Not Mentioned', max_length=50),
        ),
    ]
