# Generated by Django 5.0.1 on 2024-03-14 09:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FO_APP', '0002_remove_products_type_alter_products_category_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='category',
            field=models.CharField(choices=[('Not Mentioned', 'Not Mentioned'), ('Soups-Veg', 'Soups-Veg'), ('Soups-Non Veg', 'Soups-Non Veg'), ('Starters-Egg', 'Starters-Egg'), ('Starters-Veg', 'Starters-Veg'), ('Starters-Non Veg Special', 'Starters_Non Veg Special'), ('Non Veg Starters-Chicken', 'Non Veg Starters-Chicken'), ('Non Veg Starters-Mutton', 'Non Veg Starters-Mutton'), ('SeaFood Starters', 'SeaFood Starters'), ('Rice & Noodles-Veg', 'Rice & Noodles-Veg'), ('Rice & Noodles-Non Veg', 'Rice & Noodles-Non Veg'), ('Rice & Noodles-Egg', 'Rice & Noodles-Egg'), ('Veg Gravies', 'Veg Gravies'), ('Non Veg Gravies', 'Non Veg Gravies'), ('Biriyani Varieties', 'Biriyani Varieties'), ('Dosa Varities', 'Dosa Varities'), ('Breads', 'Breads'), ('MilkShakes', 'MilkShakes'), ('Fresh Juices', 'Fresh Juices'), ('Desserts', 'Desserts'), ('Sodas', 'Sodas')], default='Not Mentioned', max_length=50),
        ),
        migrations.AlterField(
            model_name='products',
            name='t_type',
            field=models.CharField(choices=[('Not Mentioned', 'Not Mentioned'), ('All', 'All'), ('Breakfast', 'Breakfast'), ('Lunch', 'Lunch'), ('Dinner', 'Dinner')], default='Not Mentioned', max_length=50),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
