# Generated by Django 5.0.1 on 2024-03-15 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FO_APP', '0003_alter_products_category_alter_products_t_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='description',
        ),
    ]
