# Generated by Django 5.0.1 on 2024-03-10 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FO_APP', '0005_users_alter_cartitem_quantity_alter_product_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='Customers',
        ),
    ]
