# Generated by Django 5.0.1 on 2024-03-10 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FO_APP', '0006_rename_users_customers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('phone', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='Customers',
        ),
    ]
