# Generated by Django 5.0.1 on 2024-03-11 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FO_APP', '0007_customer_delete_customers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='user',
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
